[package]
name = "smarty-rust-proc-macro"
edition = "2021"
description = "The official client macro for creating Smarty APIs from Rust"
license = "Apache-2.0"

version.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
proc-macro = true

[dependencies]
darling = "0.20.1"
quote = "1.0.28"
syn = "2.0.18"
